---
spring:
  profiles: PROD

server:
  port: 9093


tracker:
  config:
    topics: devAllTenants
    egwUrl: http://localhost:9090/egw/2/1d09cc5bff2245499bc4260385691582/single/json
    kafkaConfig:
      kafkaBrokers: "localhost:9092"
      groupName: "ETL-1-6"
      zookeeperConnectionString: "localhost:2181"
      consumerTimeoutMilliseconds: 10000
      kafkaHostsConnectionString : "localhost:9092"
      streamsPerTopic: 2







